#!/usr/bin/env python


## \namespace reduction::applications::wxARCSReductionApp
## GUI interface for ARCSReductionApp
##
## This GUI interface helps users to reduce ARCS data to
## S(Q,E).
##
## The GUI interface is mostly automatically generated by pyregui package.
## But the GUI toolkit for pyregui has been overloaded to achieve better user experience.
##
## The pyregui package is still a prototype. So this application will evolve as
## pyregui moves to better and more stable design.
##


from ARCSReductionApp import ARCSReductionApp as base
class App(base):

    __doc__ = base.__doc__

    class Inventory( base.Inventory ):
        pass

    def _defaults(self):
        self.inventory.reducer.inventory.gui = 1
        return

    pass # end of App

import journal
journal.error( "pyre.inventory" ).deactivate()
journal.debug( "pyregui" ).activate()

def main():
    appfilename = "ARCSReductionApp.py"
    from pyregui.pyreui import runApp, findExecutable
    exe = findExecutable( appfilename )
    
    from reduction.applications.pyregui_ext import wx
    runApp( App, exe, wx )
    return



if __name__ == "__main__": main()
